name: eShopSoa
on: [push]
jobs:
  run-unit-tests:
    runs-on: windows-latest
    steps:
      - run: echo "It's dummy content before tests running would be implemented"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."